"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
import sys
from datetime import timedelta
from pathlib import Path
from typing import Any, cast

import dj_database_url
import environ
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
env.read_env(BASE_DIR / ".env")
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")
DJANGO_ENV = env(
    "DJANGO_ENV", default="development"
)  # development|ci|staging|production
IS_PROD = DJANGO_ENV == "production"
REQUIRE_SECRETS = DJANGO_ENV in {"production", "staging"}
IS_TESTING = (
    "PYTEST_CURRENT_TEST" in os.environ
    or "pytest" in sys.argv[0]
    or "test" in sys.argv
)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS: list[str] = cast(
    list[str],
    env.list(
        "DJANGO_ALLOWED_HOSTS",
        default=["localhost", "127.0.0.1"],
    ),
)
CORS_ALLOWED_ORIGINS: list[str] = cast(
    list[str], env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=[])
)
API_KEY_THROTTLE_RATE = env("API_KEY_THROTTLE_RATE", default="500/min")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_prometheus",
    "django_extensions",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "accounts",
    "api_keys",
    "integrations",
    "farms",
    "ndvi",
    "weather",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "django.log"),
        },
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console", "file"], "level": "INFO"},
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# --- Database ---
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=IS_PROD,
    )
}

# --- Prometheus DB instrumentation ---
_engine = DATABASES["default"].get("ENGINE")
if _engine == "django.db.backends.postgresql":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
elif _engine == "django.db.backends.postgresql_psycopg2":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
elif _engine == "django.db.backends.mysql":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.mysql"
elif _engine == "django.db.backends.sqlite3":
    # optional:
    # DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.sqlite3"
    pass

# --- MySQL specific tuning ---
if DATABASES["default"].get("ENGINE") in {
    "django.db.backends.mysql",
    "django_prometheus.db.backends.mysql",
}:
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update(
        {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES',"
            "time_zone='+00:00'",
            "charset": "utf8mb4",
            "use_unicode": True,
        }
    )
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# --- Pytest: in-memory SQLite ---
if IS_TESTING:
    DATABASES = {
        # keep plain sqlite OR switch to django_prometheus.db.backends.sqlite3
        # (optional)
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}
    }


# Caches
def _redis_cache(location: str) -> dict[str, Any]:
    return {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": location,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }


REDIS_URL = env("REDIS_URL", default=None)

if REDIS_URL:
    default_cache_config = _redis_cache(REDIS_URL)
    throttle_cache_config = dict(default_cache_config)
else:
    default_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    }
    throttle_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "throttle",
    }

if IS_PROD and not REDIS_URL:
    raise ImproperlyConfigured("Set REDIS_URL for production caching")

CACHES = {
    "default": default_cache_config,
    "throttle": throttle_cache_config,
}

DJANGO_REDIS_IGNORE_EXCEPTIONS = not IS_PROD


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

FRONTEND_RESET_URL = env("FRONTEND_RESET_URL", default="")

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@localhost")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "api_keys.authentication.ApiKeyAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "api_keys.throttling.ApiKeyRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/min",
        "register": "5/min",
        "login": "10/min",
        "token_refresh": "20/min",
        "password_reset": "5/min",
        "password_reset_confirm": "10/min",
        "api_key": env("API_KEY_THROTTLE_RATE", default="10/min"),
    },
    "EXCEPTION_HANDLER": "config.api.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

AUTHENTICATION_BACKENDS = [
    "accounts.auth_backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("SIMPLE_JWT_ACCESS_MINUTES", default=15)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("SIMPLE_JWT_REFRESH_DAYS", default=7)
    ),
    "ISSUER": env("SIMPLE_JWT_ISSUER", default="weather-apis"),
    "AUDIENCE": env("SIMPLE_JWT_AUDIENCE", default="nextcloud"),
}

INTEGRATION_JWT_ACCESS_MINUTES = env.int(
    "INTEGRATION_JWT_ACCESS_MINUTES",
    default=5,
)

DJANGO_API_KEY_PEPPER = env("DJANGO_API_KEY_PEPPER", default=None)

if DJANGO_API_KEY_PEPPER is None:
    if REQUIRE_SECRETS:
        raise ImproperlyConfigured(
            "Set the DJANGO_API_KEY_PEPPER environment variable"
        )
    # dev/ci/tests default (not a real secret)
    DJANGO_API_KEY_PEPPER = "dev-pepper"

# Nextcloud request signing (HMAC)
NEXTCLOUD_HMAC_ENABLED = env.bool("NEXTCLOUD_HMAC_ENABLED", default=True)
NEXTCLOUD_HMAC_MAX_SKEW_SECONDS = env.int(
    "NEXTCLOUD_HMAC_MAX_SKEW_SECONDS",
    default=300,
)
NEXTCLOUD_HMAC_NONCE_TTL_SECONDS = env.int(
    "NEXTCLOUD_HMAC_NONCE_TTL_SECONDS",
    default=360,
)
NEXTCLOUD_HMAC_CACHE_ALIAS = env(
    "NEXTCLOUD_HMAC_CACHE_ALIAS", default="default"
)

# HMAC secret rotation overlap window (seconds).
# Default: 72 hours to allow propagation while limiting exposure if a secret
# leaks.
INTEGRATIONS_HMAC_PREVIOUS_TTL_SECONDS = env.int(
    "INTEGRATIONS_HMAC_PREVIOUS_TTL_SECONDS",
    default=259200,
)

_nextcloud_hmac_clients_raw = env("NEXTCLOUD_HMAC_CLIENTS_JSON", default="{}")
try:
    _nextcloud_hmac_clients_parsed = json.loads(_nextcloud_hmac_clients_raw)
except json.JSONDecodeError as exc:  # pragma: no cover
    raise ImproperlyConfigured(
        "NEXTCLOUD_HMAC_CLIENTS_JSON must be valid JSON"
    ) from exc

if not isinstance(_nextcloud_hmac_clients_parsed, dict):  # pragma: no cover
    raise ImproperlyConfigured(
        "NEXTCLOUD_HMAC_CLIENTS_JSON must be a JSON object"
    )

NEXTCLOUD_HMAC_CLIENTS: dict[str, str] = {}
for _client_id, _secret in _nextcloud_hmac_clients_parsed.items():
    if not isinstance(_client_id, str) or not isinstance(
        _secret, str
    ):  # pragma: no cover
        raise ImproperlyConfigured(
            "NEXTCLOUD_HMAC_CLIENTS_JSON must map strings to strings"
        )
    if not _client_id or not _secret:  # pragma: no cover
        raise ImproperlyConfigured(
            "NEXTCLOUD_HMAC_CLIENTS_JSON cannot contain empty keys or values"
        )
    NEXTCLOUD_HMAC_CLIENTS[_client_id] = _secret

if NEXTCLOUD_HMAC_CACHE_ALIAS not in CACHES:  # pragma: no cover
    raise ImproperlyConfigured(
        "NEXTCLOUD_HMAC_CACHE_ALIAS must be one of: "
        f"{', '.join(CACHES.keys())}"
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SPECTACULAR_SETTINGS = {
    "TITLE": "Weather APIs",
    "DESCRIPTION": "REST API for user authentication and "
    "API key lifecycle management.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key",
            },
        },
    },
    "ENUM_NAME_OVERRIDES": {
        "ApiKeyScopeEnum": "api_keys.models.ApiKeyScope",
        "ApiKeyScopeValueEnum": ("read", "write", "admin"),
    },
}


REST_FRAMEWORK = cast(dict[str, Any], REST_FRAMEWORK)

if IS_TESTING:
    disable_throttle = env.bool(
        "DISABLE_THROTTLE_IN_TESTS",
        default=False,
    )
    if disable_throttle:
        REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []

# NDVI defaults and limits
NDVI_ENGINE = env("NDVI_ENGINE", default="sentinelhub")
NDVI_MAX_AREA_KM2 = env.float("NDVI_MAX_AREA_KM2", default=5000.0)
NDVI_MAX_DATERANGE_DAYS = env.int("NDVI_MAX_DATERANGE_DAYS", default=370)
NDVI_LOCK_TIMEOUT_SECONDS = env.int("NDVI_LOCK_TIMEOUT_SECONDS", default=300)
NDVI_CACHE_TTL_TIMESERIES_SECONDS = env.int(
    "NDVI_CACHE_TTL_TIMESERIES_SECONDS",
    default=86400,
)
NDVI_CACHE_TTL_LATEST_SECONDS = env.int(
    "NDVI_CACHE_TTL_LATEST_SECONDS",
    default=21600,
)
NDVI_DEFAULT_STEP_DAYS = env.int("NDVI_DEFAULT_STEP_DAYS", default=7)
NDVI_DEFAULT_MAX_CLOUD = env.int("NDVI_DEFAULT_MAX_CLOUD", default=30)
NDVI_DEFAULT_LOOKBACK_DAYS = env.int("NDVI_DEFAULT_LOOKBACK_DAYS", default=14)
NDVI_MANUAL_REFRESH_COOLDOWN_SECONDS = env.int(
    "NDVI_MANUAL_REFRESH_COOLDOWN_SECONDS",
    default=900,
)
NDVI_REQUEST_TIMEOUT_SECONDS = env.float(
    "NDVI_REQUEST_TIMEOUT_SECONDS",
    default=20,
)
NDVI_RASTER_ENGINE_PATH = env(
    "NDVI_RASTER_ENGINE_PATH",
    default="ndvi.raster.sentinelhub_engine.SentinelHubRasterEngine",
)
NDVI_RASTER_ENGINE_NAME = env(
    "NDVI_RASTER_ENGINE_NAME",
    default="sentinelhub",
)
NDVI_RASTER_MAX_SIZE = env.int("NDVI_RASTER_MAX_SIZE", default=1024)
NDVI_RASTER_DEFAULT_SIZE = env.int(
    "NDVI_RASTER_DEFAULT_SIZE",
    default=512,
)
NDVI_RASTER_MANUAL_QUEUE_COOLDOWN_SECONDS = env.int(
    "NDVI_RASTER_MANUAL_QUEUE_COOLDOWN_SECONDS",
    default=900,
)
NDVI_RASTER_CACHE_TTL_SECONDS = env.int(
    "NDVI_RASTER_CACHE_TTL_SECONDS",
    default=86400,
)

# Weather defaults
WEATHER_PROVIDER_DEFAULT = env(
    "WEATHER_PROVIDER_DEFAULT",
    default="open_meteo",
)
WEATHER_DEFAULT_TZ = env(
    "WEATHER_DEFAULT_TZ",
    default="Africa/Nairobi",
)
OPEN_METEO_BASE_URL = env(
    "OPEN_METEO_BASE_URL",
    default="https://api.open-meteo.com/v1/forecast",
)
NASA_POWER_BASE_URL = env(
    "NASA_POWER_BASE_URL",
    default="https://power.larc.nasa.gov/api/temporal/daily/point",
)
WEATHER_CACHE_TTL_CURRENT_S = env.int(
    "WEATHER_CACHE_TTL_CURRENT_S",
    default=120,
)
WEATHER_CACHE_TTL_DAILY_S = env.int(
    "WEATHER_CACHE_TTL_DAILY_S",
    default=900,
)
WEATHER_CACHE_TTL_WEEKLY_S = env.int(
    "WEATHER_CACHE_TTL_WEEKLY_S",
    default=1800,
)
WEATHER_MAX_RANGE_DAYS = env.int(
    "WEATHER_MAX_RANGE_DAYS",
    default=366,
)

# Celery
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=REDIS_URL or "memory://")
CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default="cache+memory://",
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = env.bool(
    "CELERY_TASK_ALWAYS_EAGER",
    default=IS_TESTING,
)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BEAT_SCHEDULE = {
    "ndvi-daily-refresh": {
        "task": "ndvi.tasks.enqueue_daily_refresh",
        "schedule": crontab(hour=3, minute=15),
    },
    "ndvi-weekly-gap-fill": {
        "task": "ndvi.tasks.enqueue_weekly_gap_fill",
        "schedule": crontab(hour=4, minute=0, day_of_week="sun"),
    },
}
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "Africa/Nairobi"
