# Generated by Django 5.1.15 on 2025-12-25 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "client_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("secret", models.CharField(max_length=128)),
                (
                    "previous_secret",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "previous_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["client_id", "is_active"],
                        name="integration_client__29e509_idx",
                    )
                ],
            },
        ),
    ]
