# Generated by Django 5.1.15 on 2025-12-18 09:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "centroid_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-90")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("90")
                            ),
                        ],
                    ),
                ),
                (
                    "centroid_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-180")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("180")
                            ),
                        ],
                    ),
                ),
                (
                    "bbox_south",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-90")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("90")
                            ),
                        ],
                    ),
                ),
                (
                    "bbox_west",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-180")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("180")
                            ),
                        ],
                    ),
                ),
                (
                    "bbox_north",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-90")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("90")
                            ),
                        ],
                    ),
                ),
                (
                    "bbox_east",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-180")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("180")
                            ),
                        ],
                    ),
                ),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "created_at"],
                        name="farms_farm_owner_i_ea8972_idx",
                    ),
                    models.Index(
                        fields=["owner", "slug"],
                        name="farms_farm_owner_i_4b57e3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "slug"), name="uniq_farm_owner_slug"
                    ),
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="uniq_farm_owner_name"
                    ),
                ],
            },
        ),
    ]
