# Generated by Django 5.1.15 on 2025-12-18 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NdviJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=64)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("refresh_latest", "Refresh latest"),
                            ("gap_fill", "Gap fill"),
                            ("backfill", "Backfill"),
                        ],
                        max_length=32,
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "step_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_cloud",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "lookback_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "request_hash",
                    models.CharField(db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_jobs",
                        to="farms.farm",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "farm", "status"],
                        name="ndvi_ndvijo_owner_i_df2efc_idx",
                    ),
                    models.Index(
                        fields=["request_hash"],
                        name="ndvi_ndvijo_request_98bc16_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["queued", "running"])
                        ),
                        fields=("owner", "farm", "engine", "request_hash"),
                        name="uniq_active_ndvi_job",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NdviObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=64)),
                ("bucket_date", models.DateField()),
                ("mean", models.FloatField()),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("sample_count", models.IntegerField(blank=True, null=True)),
                ("cloud_fraction", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_observations",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["farm", "bucket_date"],
                        name="ndvi_ndviob_farm_id_c99de5_idx",
                    ),
                    models.Index(
                        fields=["engine", "bucket_date"],
                        name="ndvi_ndviob_engine_9431d2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("farm", "engine", "bucket_date"),
                        name="uniq_ndvi_observation_farm_engine_bucket",
                    )
                ],
            },
        ),
    ]
