# Generated by Django 5.1.15 on 2025-12-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndvi", "0002_ndvirasterartifact"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ndvirasterartifact",
            new_name="ndvi_ndvira_owner_i_adcf1f_idx",
            old_name="ndvi_ndvir_owner_id_5f4203_idx",
        ),
        migrations.RenameIndex(
            model_name="ndvirasterartifact",
            new_name="ndvi_ndvira_engine_f25a70_idx",
            old_name="ndvi_ndvir_engine__a0225e_idx",
        ),
        migrations.AlterField(
            model_name="ndvijob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("refresh_latest", "Refresh latest"),
                    ("gap_fill", "Gap fill"),
                    ("backfill", "Backfill"),
                    ("raster_png", "Raster PNG"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="engine",
            field=models.CharField(default="sentinelhub", max_length=64),
        ),
        migrations.AlterField(
            model_name="ndvirasterartifact",
            name="engine",
            field=models.CharField(max_length=64),
        ),
    ]
