# Generated by Django 5.1.15 on 2025-12-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_apikey_scope_last_used_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_user_id_af1bd6_idx",
            old_name="api_keys_user_revoked_expires_idx",
        ),
    ]
